#!/usr/bin/env bash
## Description: Use Cypress in "runner" mode.
##
## Usage: cypress-run [arguments]
## Example: "ddev cypress-run --browser chrome"

export DISPLAY=:99
Xvfb :99 -screen 0 1280x720x24 &>/dev/null &
sleep 1

cypress run "$@"
