#!/usr/bin/env bash
#ddev-generated

## Description: Open an interactive Cypress window
##              https://docs.cypress.io/guides/guides/command-line#cypress-open
## Usage: cypress-open [arguments]
## Example: "ddev cypress-open --config cypress.json"

export DISPLAY=:99
Xvfb :99 -screen 0 1280x720x24 &>/dev/null &
sleep 1

cypress open --project . "$@"
