backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

site_url: 'https://www.hayahaycafe.com'

media_folder: static/images
public_folder: /images
#media_library:
#  name: cloudinary
#  use_transformations: false
#  use_secure_url: true
#  config:
#    cloud_name: hayahaycafe
#    api_key: 422136513935459
#    use_transformations: false
#    use_secure_url: true

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Page'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/start.md'
        label: 'Start Page'
        name: 'start-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: StartPage }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/contact.md'
        label: 'Contact'
        name: 'contact-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: ContactPage }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            required: false
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/gallery.md'
        label: 'Gallery'
        name: 'gallery-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: GalleryPage }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: 'Images'
            name: 'images'
            widget: 'list'
            fields:
              - { name: src, label: Image, widget: image }
              - { name: alt, label: Alt, widget: string }
              - { name: title, label: Title, widget: string, required: false }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/about.md'
        label: 'About'
        name: 'about-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: DefaultPage }
          - { label: Slug, name: slug, widget: hidden, default: 'about' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            required: false
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/menu.md'
        label: 'Brunch Menu'
        name: 'menu-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: MenuPage }
          - { label: Slug, name: slug, widget: hidden, default: 'menu' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: 'Images'
            name: 'images'
            widget: 'list'
            fields:
              - { name: src, label: Image, widget: image }
              - { name: alt, label: Alt, widget: string }
              - { name: title, label: Title, widget: string, required: false }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            required: false
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/dinner-menu.md'
        label: 'Dinner Menu'
        name: 'dinner-menu-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: MenuPage }
          - { label: Slug, name: slug, widget: hidden, default: 'dinner-menu' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: 'Images'
            name: 'images'
            widget: 'list'
            fields:
              - { name: src, label: Image, widget: image }
              - { name: alt, label: Alt, widget: string }
              - { name: title, label: Title, widget: string, required: false }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            required: false
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/legal.md'
        label: 'Legal'
        name: 'legal-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: DefaultPage }
          - { label: Slug, name: slug, widget: hidden, default: 'legal' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Images, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            required: false
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

      - file: 'content/pages/data-privacy.md'
        label: 'Data Privacy'
        name: 'data-privacy-page'
        fields:
          - { label: Template, name: template, widget: hidden, default: DefaultPage }
          - { label: Slug, name: slug, widget: hidden, default: 'data-privacy' }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Header Images, name: headerImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Keywords, name: keywords, widget: string, required: false }

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: Keywords, name: keywords, widget: string, required: false }
              - { label: Language, name: language, widget: string, required: false }
          - label: 'Location'
            name: 'location'
            widget: 'object'
            required: false
            fields:
              - label: 'Address'
                name: 'address'
                widget: 'object'
                required: false
                fields:
                  - { label: 'Company', name: company, widget: string, required: false }
                  - { label: 'Address Line 1', name: addressLine1, widget: string, required: false }
                  - { label: 'Address Line 2', name: addressLine2, widget: string, required: false }
                  - { label: 'Province', name: province, widget: string, required: false }
                  - { label: 'Postal Code', name: postalCode, widget: string, required: false }
                  - { label: 'Country', name: country, widget: string, required: false }
              - { label: 'What3words Address', name: what3WordsAddress, widget: string, required: false }
          - { label: 'Opening Hours', name: openingHours, widget: markdown, required: false }
          - label: 'Social Media'
            name: 'socialMedia'
            required: false
            widget: 'list'
            fields:
              - { label: Url, name: url, widget: string }
              - name: 'type'
                label: 'Typ'
                widget: 'select'
                options:
                  - { label: 'Facebook', value: 'facebook' }
                  - { label: 'Instagram', value: 'instagram' }
                  - { label: 'Trip Advisor', value: 'tripadvisor' }