name: Run Cypress
on:
  pull_request:
    branches:
      - master
jobs:
  cypress:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache public folder
        uses: actions/cache@v2
        with:
          path: public
          key: cache-public-${{ github.sha }}
          restore-keys: |
            cache-public-
      - name: Cache cache folder
        uses: actions/cache@v2
        with:
          path: .cache
          key: cache-.cache-${{ github.sha }}
          restore-keys: |
            cache-.cache-
      - name: Run Cypress
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          SITE_RECAPTCHA_KEY: ${{ secrets.SITE_RECAPTCHA_KEY }}
          SITE_RECAPTCHA_SECRET: ${{ secrets.SITE_RECAPTCHA_SECRET }}
          NETLIFY_SITE_URL: ${{ secrets.NETLIFY_SITE_URL }}
          CYPRESS_NETLIFY_CMS_EMAIL: ${{ secrets.CYPRESS_NETLIFY_CMS_EMAIL }}
          CYPRESS_NETLIFY_CMS_PASSWORD: ${{ secrets.CYPRESS_NETLIFY_CMS_PASSWORD }}
        run: |
          npm ci
          echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.development
          echo NETLIFY_SITE_URL=$NETLIFY_SITE_URL >> .env.development
          npm run test:e2e:ci
  lighthouse:
    name: Lighthouse Audits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
      - name: Run Cypress
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_ENV: test
        run: |
          npm ci
          npm run lighthouse:ci:record
