name: Run ESLint
on:
  pull_request:
    branches:
      - master
jobs:
  eslint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run ESLint
        run: |
            npm ci -D
            npm run lint
