name: Run Jest
on:
  pull_request:
    branches:
      - master
jobs:
  jest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
      - name: Run Jest
        run: |
            npm ci -D
            npm run test
