name: Build project and Run Lighthouse CI
on: push
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: ./lighthouserc.json